version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: korp-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Korp@2026!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: always

volumes:
  sqlserver-data: